### ISSUE TITLE
Add support for Github

### ISSUE THREAD

**Issue by joshghent** [jammie1903/merge-request-queryer#6]
This will require a big refactor, but would be good to split the code up like this.
In the report generator, split out the gitlab specific code and create a common library that can sit above the gitlab and GitHub specific api calls - with Typescript this should be a breeze to make sure we always get the same format data back.
Add a new environment variable for the git type, either GITLAB or GITHUB for now (support for others can come later off the back of these changes).

**Comment by jammie1903** [comment]
Its a good idea, right now i cant even run this project because I no longer have access to a gitlab instance. :+1:

**Comment by joshghent** [comment]
Cool, I'll try and work on this soon

**Comment by jammie1903** [comment]
Go for it, if i get the chance, i might try and add VSTS support too, though its a bit different so i hope its possible

**Comment by joshghent** [comment]
@jammie1903 Yeah I mean if it's got an API then I guess we can integrate with it
